# Generated by Django 5.1.4 on 2024-12-10 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proyecto', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripcion del proyecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion del proyecto')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion del proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='Imagen de perfil', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Breve biografia del usuario', null=True)),
                ('user', models.OneToOneField(help_text='Usuario al que pertenece este perfil', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
