# Generated by Django 5.1.4 on 2024-12-10 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la tarea', max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion de la tarea', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creacion de la tarea')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de ultima actualizacion de la tarea')),
                ('estado', models.CharField(choices=[('todo', 'Por hacer'), ('doing', 'En progreso'), ('done', 'Hecho')], default='todo', help_text='Estado de la tarea', max_length=20)),
                ('adjunto', models.FileField(blank=True, help_text='Archivo adjunto', null=True, upload_to='adjuntos/')),
                ('propietario', models.ForeignKey(blank=True, help_text='Usuario propietario de la tarea', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que pertenece esta tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.proyecto')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
